platform :ios, '18.0'

target 'Runner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Runner
  pod 'AccessCheckoutSDK', '~> 4.1'

  target 'RunnerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end


